Изменены стили, добавлены переменные
frontend-park-mail-ru/2024_1_commandName pull request #13
Opened 2024-03-23 21:30 UTC by IvanNaum

2024-03-24 08:49 UTC, johnSamilin requested changes

2024-03-24 08:49 UTC, johnSamilin commented on src/styles/index.css
> +    --hover-transition: all 0.3s;
это разве hover transition? нельзя вводить в заблуждение названиями переменных

2024-03-24 08:49 UTC, johnSamilin commented on src/Components/Profile/Profile.hbs
> +                    onerror="if (this.src != 'img/avatar.jpg') this.src = 'img/avatar.jpg';"
кажется, это можно сделать через <picture>:
```
<picture>
  <source srcset={{avatar}} />
  <img src="img/avatar.jpg" />
</picture>
```

2024-03-24 08:49 UTC, johnSamilin commented on src/Components/Profile/Profile.hbs
> +            <hr />
попробуй без hr, эти заголовки (кстати, почему заголовки, семантически?) можно стилизовать так, как если бы их разделяли hr

2024-03-24 08:49 UTC, johnSamilin commented on src/styles/index.css
> +    clear: both;
у вас же вроде не используется float, зачем тут clear?

2024-03-24 08:49 UTC, johnSamilin commented on src/styles/index.css
> +    width: 96%;
почему 96% выглядит, как будто это магическое число, просто подобранное эмпирически

2024-03-24 08:49 UTC, johnSamilin commented on src/styles/index.css
> +    background-color: #3F708F;
Сюда, кажется, переменная не доехала

2024-03-24 15:17 UTC, IvanNaum commented on src/styles/index.css
> +    --hover-transition: all 0.3s;
а почему нет? я его использую для hover

2024-03-24 15:44 UTC, johnSamilin commented on src/styles/index.css
> +    --hover-transition: all 0.3s;
А если мне нужно анимировать что-то на focus или при добавлении класса, то мне эту переменную использовать или другую завести с тем же значением?

2024-03-24 16:48 UTC, johnSamilin commented on src/styles/index.css
> +    --hover-transition: all 0.3s;
Да и потом, что именно анимируется на hover? По коду кажется, что все и всегда

2024-03-25 09:28 UTC, IvanNaum commented on src/styles/index.css
> +    --hover-transition: all 0.3s;
fixed

2024-03-25 09:28 UTC, IvanNaum commented on src/Components/Profile/Profile.hbs
> +                    onerror="if (this.src != 'img/avatar.jpg') this.src = 'img/avatar.jpg';"
fixed

2024-03-25 09:28 UTC, IvanNaum commented on src/Components/Profile/Profile.hbs
> +            <hr />
fixed

2024-03-25 09:29 UTC, IvanNaum commented on src/styles/index.css
> +    clear: both;
fixed

2024-03-25 09:29 UTC, IvanNaum commented on src/styles/index.css
> +    width: 96%;
fixed

2024-03-25 09:29 UTC, IvanNaum commented on src/styles/index.css
> +    background-color: #3F708F;
fixed

2024-03-25 10:21 UTC, johnSamilin approved these changes

2024-03-25 10:23 UTC, merged