Routes
frontend-park-mail-ru/2024_1_commandName pull request #14
Opened 2024-03-29 15:18 UTC by oFem1m

Добавил router

2024-03-30 12:23 UTC, johnSamilin requested changes

2024-03-30 12:23 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +        this.handleLogout = this.handleLogout.bind(this);
тут можно обойтись без привязки контекста

2024-03-30 12:23 UTC, johnSamilin commented on src/Pages/LoginPage.js
> +        this.formCallback = this.formCallback.bind(this);
и здесь тоже

2024-03-30 12:23 UTC, johnSamilin commented on src/utils/router.js
> +window.addEventListener('popstate', handleRouting);
если у нас уже есть обработчик pushstate, зачем тогда каждый раз вызывать `handleRouting()`?

2024-03-30 12:23 UTC, johnSamilin commented on src/utils/router.js
> +export function handleRouting() {
Еще было бы неплохо обрабатывать первоначальный урл, то есть как только ты ввел в адресной строке ссылку `https://chatme.site/chat/ABCDE` и жмякнул enter, чтобы открывалась уже страница диалога

2024-03-30 12:23 UTC, johnSamilin commented on src/config/config.js
> +    '/chat': ChatPage,
а параметры как передаваться будут? например, /chat/ABCDE, чтобы в диалог попасть

2024-03-30 12:31 UTC, johnSamilin commented on src/Components/ChatList/ChatList.js
> -                goToPage(ProfilePage);
а еще может быть `goToPage` должна вызывать `window.history.pushState`, раз уж исторически она использовалась для навигации?

2024-03-30 22:24 UTC, oFem1m commented on src/utils/router.js
> +window.addEventListener('popstate', handleRouting);
обработчика pushState нет, поэтому на каждой странице при переходе вызывается handleRouting. Когда я попытался обработку воткнуть сюда (сразу в router), то почему-то не заработало

2024-03-31 05:41 UTC, johnSamilin commented on src/utils/router.js
> +window.addEventListener('popstate', handleRouting);
1. Надо было разобраться, почему не заработало и что именно :)
2. Да, сорян, pushState нет, но его можно симулировать через window.dispatchEvent(new PopStateEvent('popstate')), расположенный внутри goToPage, например

2024-04-01 12:58 UTC, johnSamilin requested changes

2024-04-01 12:58 UTC, johnSamilin commented on src/utils/API/common.js
> +        goToPage('login');
кажется, вот тут нужно throw кидать или return делать, чтобы код, вызывающий этот запрос, не пытался отрендерить что-то (данных у него все равно не будет нужных). Но при этом приложение не должно ломаться из-за необработанного исключения.
и еще один момент: если на странице будет 10 параллельных запросов, но ты не авторизован, то произойдет 10 редиректов на один и тот же урл по мере того, как запросы будут выполняться. Если у тебя при этом плохой интернет, то между ними будет проходить какое-то время и это станет заметно. Наверное нужно добавить какой-то флаг и проверять его значение, типа нужно ли перенаправление делать

2024-04-01 12:58 UTC, johnSamilin commented on src/utils/router.js
> +    const page = ROUTES[path] || ROUTES['*']; // Используем Page404 при неизвестном пути
а параметры? добавим сюда проверку роута по регулярке?

2024-04-01 19:31 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +                        window.history.pushState(
почему не `goToPage`?

2024-04-02 10:30 UTC, johnSamilin approved these changes

2024-04-02 19:36 UTC, merged