Добавлена страница создания группы
frontend-park-mail-ru/2024_1_commandName pull request #17
Opened 2024-04-05 11:44 UTC by IvanNaum

2024-04-05 11:50 UTC, IvanNaum commented
Требует согласования API с бэкендом

2024-04-05 14:24 UTC, johnSamilin requested changes

2024-04-05 14:24 UTC, johnSamilin commented on src/Components/ChatList/ChatList.css
> +#contacts_btn, #create_group_btn {
может правильней вынести этот стиль в класс .chat-list-button?

2024-04-05 14:24 UTC, johnSamilin commented on src/Components/Form/Form.hbs
> +                        {{this.name}} {{this.surname}} @{{this.username}}
Лучше придумать какой-то способ с использованием подшаблонов, потому что общий компонент (Form) не должен знать о частных случаях. Если вы завтра будете использовать ее для рендера формы обратной связи с чекбоксами, то придется общий компонент переделывать и это приведет к большому регрессу

2024-04-05 14:24 UTC, johnSamilin commented on src/Components/Form/Form.hbs
> +                        {{this.name}} {{this.surname}} @{{this.username}}
или может быть {{this.label}}

2024-04-05 14:24 UTC, johnSamilin commented on src/Pages/CreateGroupPage.js
> +        const userList = event.target.querySelectorAll(
можно использовать `new FormData(event.target)`

2024-04-05 14:24 UTC, johnSamilin commented on src/Pages/CreateGroupPage.js
> +                    enableRedirect(true);
кажется, в момент когда ты попадаешь на эту страницу, флаг уже должен быть true

2024-04-05 14:24 UTC, johnSamilin commented on src/index.js
> +    return arg1 == arg2 ? options.fn(this) : options.inverse(this);
===

2024-04-05 14:24 UTC, johnSamilin commented on src/index.js
> +    return arg1 != arg2 ? options.fn(this) : options.inverse(this);
!==

2024-04-05 14:24 UTC, johnSamilin commented on src/utils/API/ChatAPI.js
> +                'There was a problem with the fetch operation:',
Лучше еще описать, какую конкретно операцию не удалось выполнить

2024-04-09 06:13 UTC, IvanNaum commented on src/utils/API/ChatAPI.js
> +                'There was a problem with the fetch operation:',
fixed

2024-04-09 06:13 UTC, IvanNaum commented on src/index.js
> +    return arg1 != arg2 ? options.fn(this) : options.inverse(this);
fixed

2024-04-09 06:13 UTC, IvanNaum commented on src/index.js
> +    return arg1 == arg2 ? options.fn(this) : options.inverse(this);
fixed

2024-04-09 06:13 UTC, IvanNaum commented on src/Pages/CreateGroupPage.js
> +                    enableRedirect(true);
fixed

2024-04-09 16:48 UTC, IvanNaum commented on src/Components/ChatList/ChatList.css
> +#contacts_btn, #create_group_btn {
fixed

2024-04-09 16:52 UTC, IvanNaum commented on src/Components/Form/Form.hbs
> +                        {{this.name}} {{this.surname}} @{{this.username}}
fixed

2024-04-10 07:47 UTC, IvanNaum commented on src/Pages/CreateGroupPage.js
> +        const userList = event.target.querySelectorAll(
`new FormData(event.target)` возвращает пустую форму

2024-04-10 07:59 UTC, johnSamilin approved these changes

2024-04-10 08:26 UTC, merged