Authorization
frontend-park-mail-ru/2024_1_commandName pull request #2
Opened 2024-03-04 17:02 UTC by IvanNaum

2024-03-04 18:41 UTC, johnSamilin commented
@IvanNaum @oFem1m  Решите пожалуйста, как вы будете писать описание коммитов (на русском или английском) и зафиксируйте в readme

2024-03-04 19:06 UTC, johnSamilin requested changes

2024-03-04 19:06 UTC, johnSamilin commented on src/styles/index.css
> +#error-message {
на странице может быть только одно сообщение об ошибке?

2024-03-04 19:06 UTC, johnSamilin commented on src/utils/API/AuthAPI.js
> +            const response = await fetch('http://localhost:8080/checkAuth', {
эта часть везде одинаковая, ее можно вынести в отдельный метод, типа `this.createBasicRequest('GET', 'checkAuth')`
и вообще все методы на 90% одинаковые

2024-03-04 19:06 UTC, johnSamilin commented on src/utils/valid.js
> + * @returns {Object} - Объект с результатом валидации.
тут вместо Object лучше расписать структуру объекта, а то непонятно, что функция вернет

2024-03-04 19:15 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +        this.#parent.innerHTML = '';
то есть писать можно?

2024-03-04 19:26 UTC, johnSamilin commented on src/Pages/LoginPage.js
> +        this.#parent.innerHTML = '';
добавлять что-то в родительский можно, да, но все, что компонент добавит, будет в его зоне ответственности и за эти границы выходить не надо, чтобы другим не помешать

2024-03-05 06:36 UTC, johnSamilin requested changes

2024-03-05 06:36 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +export default class ChatPage {
а что делает страница чатов в ПР под названием authorization?

2024-03-05 16:40 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +        this.#parent.innerHTML = '';
fixed

2024-03-05 16:40 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +        notExistsAccauntButton.style = 'margin-top: 5px;';
можно, fixed

2024-03-05 16:40 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +        const notExistsAccauntButton = document.createElement('button');
fixed

2024-03-05 16:40 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +    setError; // TODO
fixed

2024-03-05 16:40 UTC, IvanNaum commented on server/index.js
> +app.use(express.static(path.join(__dirname, '..', 'node_modules')));
ничего, fixed

2024-03-05 16:52 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +                    console.log(data);
fixed

2024-03-05 17:04 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +        signinForm.addEventListener('submit', function (event) {
fixed

2024-03-05 19:02 UTC, johnSamilin commented on src/Pages/RegisterPage.js
> +        this.#parent.appendChild(signupContainer);
кайф

2024-03-05 19:20 UTC, IvanNaum commented on src/Pages/RegisterPage.js
> +            const username = document.getElementById('username').value;
fixed

2024-03-05 20:24 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +                    console.error('Login failed:', error);
fixed, добавлен alert

2024-03-05 20:29 UTC, IvanNaum commented on src/utils/valid.js
> + * @returns {Object} - Объект с результатом валидации.
fixed

2024-03-05 20:37 UTC, IvanNaum commented on src/styles/index.css
> +#error-message {
fixed

2024-03-05 20:46 UTC, johnSamilin approved these changes

2024-03-05 20:47 UTC, merged