Отправка сообщений
frontend-park-mail-ru/2024_1_commandName pull request #22
Opened 2024-04-07 18:01 UTC by oFem1m

Отправка сообщений с помощью вебсокетов

2024-04-07 18:20 UTC, johnSamilin requested changes

2024-04-07 18:20 UTC, johnSamilin commented on src/Components/Chat/Chat.hbs
> +            <button class='input_send chat-input'>-></button>
&rarr;

2024-04-07 18:20 UTC, johnSamilin commented on src/Components/Message/Message.hbs
> +<div class="{{message_owner}}">
Вот тут нет ошибки?

2024-04-07 18:20 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +                this.UserId = profile.id;
А почему с большой?

2024-04-07 18:20 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +        const inputMessage = this.#parent.querySelector('#input_message').value;
.trim еще бы добавить и возможно удалить xss уже на этом этапе

2024-04-07 18:20 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +                goToPage('/chat?id=' + chatId);
А зачем тут переход?

2024-04-07 18:20 UTC, johnSamilin commented on src/utils/API/config.js
> +    baseUrl = 'chatme.site/api/v1';
Не согласен, почему от протокола зависит адрес?

2024-04-07 18:20 UTC, johnSamilin commented on src/utils/router.js
> -
Почему эту правку убрали?

2024-04-07 19:31 UTC, oFem1m commented on src/Components/Message/Message.hbs
> +<div class="{{message_owner}}">
Там теперь логика такая, что если id пользователя совпадает с id отправителя сообщения, то используется класс my_message, для которого уже заготовлены стили

2024-04-07 19:31 UTC, oFem1m commented on src/Components/Chat/Chat.hbs
> +            <button class='input_send chat-input'>-></button>
спасибо

2024-04-07 19:52 UTC, oFem1m commented on src/utils/API/config.js
> +    baseUrl = 'chatme.site/api/v1';
это для деплоя, там ngnix ругался

2024-04-07 19:52 UTC, oFem1m commented on src/utils/router.js
> -
некорректно работали стрелочки и некоторые переходы

2024-04-07 21:25 UTC, oFem1m commented on src/Pages/ChatPage.js
> +                this.UserId = profile.id;
исправил на маленькую

2024-04-07 21:41 UTC, oFem1m commented on src/Pages/ChatPage.js
> +        const inputMessage = this.#parent.querySelector('#input_message').value;
сделал

2024-04-08 07:29 UTC, johnSamilin commented on src/Components/Message/Message.hbs
> +<div class="{{message_owner}}">
так это можно прямо в шаблоне проверить типа через `class="{{isCurrentUserOwner ? 'owner' : 'noOwner'}}"'

2024-04-08 07:31 UTC, johnSamilin commented on src/utils/API/config.js
> +    baseUrl = 'chatme.site/api/v1';
тогда нужно сделать какой-то параметр, который будет определять, мы в тестовом окружении или в проде. условно, тут же переменная ENV_TYPE, которая в ветке master будет равна PROD, а в остальных - DEV

2024-04-08 07:34 UTC, johnSamilin requested changes

2024-04-08 07:34 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +        function escapeHTML(html) {
это должно быть методом класса, а еще лучше - функцией модуля utils, но точно не локальной функцией

2024-04-08 15:46 UTC, oFem1m commented on src/Pages/ChatPage.js
> +        function escapeHTML(html) {
исправил

2024-04-09 05:36 UTC, johnSamilin approved these changes

2024-04-09 18:37 UTC, johnSamilin commented on src/Pages/ChatPage.js
> +            const chat = this.#chats.splice(chatIndex, 1)[0];
проще сделать сортировку через css (свойство order)

2024-04-09 20:25 UTC, merged