WIP: Добавлен parcel, SCSS
frontend-park-mail-ru/2024_1_commandName pull request #25
Opened 2024-04-19 07:54 UTC by IvanNaum

2024-04-20 08:33 UTC, johnSamilin commented on src/index.html
> +    <link rel="stylesheet" href="./styles/index.scss">
Стили можно импортировать прямо в файле компонента через import './style.scss'

2024-05-01 19:31 UTC, johnSamilin requested changes

2024-05-01 19:31 UTC, johnSamilin commented on src/Components/Chat/Chat.scss
> +@import '../../styles/index.scss';
Index.scss должен включать в себя Chat, не наоборот

2024-05-01 19:31 UTC, johnSamilin commented on package.json
> +        "start": "parcel src/index.html --port 3000",
А где build?

2024-05-02 19:59 UTC, IvanNaum commented on package.json
> +        "start": "parcel src/index.html --port 3000",
fixed

2024-05-05 19:47 UTC, IvanNaum commented on src/Components/Chat/Chat.scss
> +@import '../../styles/index.scss';
fixed

2024-05-05 19:47 UTC, IvanNaum commented on src/index.html
> +    <link rel="stylesheet" href="./styles/index.scss">
fixed

2024-05-05 19:53 UTC, johnSamilin approved these changes

2024-05-05 19:54 UTC, merged