Оффлайн
frontend-park-mail-ru/2024_1_commandName pull request #26
Opened 2024-04-25 19:46 UTC by oFem1m

Теперь приложение работает с ограниченной функциональностью без интернета

2024-04-26 06:33 UTC, johnSamilin requested changes

2024-04-26 06:33 UTC, johnSamilin commented on src/Pages/ContactsPage.js
> +            caches.open('my-cache-v1').then(function (cache) {
давайте выберем более подходящее название для кэша

2024-04-26 06:33 UTC, johnSamilin commented on src/utils/serviceWorker.js
> +                return response;
вот это значит, что после первого же запроса реальные запросы перестанут до бека доходить и будут всегда браться из кеша. Здесь нужно проверять, есть ли у нас интернет и если нет (то есть мы в оффлайне), то отдавать кешированный запрос. Иначе fetch(event.request).then(добавление в кеш)

2024-04-26 06:33 UTC, johnSamilin commented on src/Pages/ProfilePage.js
> +            caches.open('my-cache-v1').then(function (cache) {
добавление в кеш должно происходить в одном месте (в сервис-воркере), как и получение данных из кэша (то, что ниже). То есть страница (или компонент) не должны вообще знать, как устроена работа с кешем, их задача просто данные получить

2024-04-26 06:33 UTC, johnSamilin commented on src/utils/serviceWorker.js
> +});
а как будет происходить обновление сервис-воркера? если вы завтра добавите какой-то функционал, он должен уметь переустанавливаться

2024-04-26 21:30 UTC, oFem1m commented on src/Pages/ContactsPage.js
> +            caches.open('my-cache-v1').then(function (cache) {
исправил

2024-04-26 21:31 UTC, oFem1m commented on src/utils/serviceWorker.js
> +                return response;
теперь ответы из сети кешируются, а если ответа нет - достается кеш

2024-04-26 21:31 UTC, oFem1m commented on src/Pages/ProfilePage.js
> +            caches.open('my-cache-v1').then(function (cache) {
теперь всё в воркере

2024-04-26 21:37 UTC, oFem1m commented on src/utils/serviceWorker.js
> +});
а теперь он просто кеширует все ответы (включая все файлы)

и при каждом обновлении страницы он регистрируется заново

2024-04-28 18:46 UTC, johnSamilin approved these changes

2024-04-28 20:44 UTC, merged