Components
frontend-park-mail-ru/2024_1_commandName pull request #5
Opened 2024-03-09 16:52 UTC by IvanNaum

2024-03-09 17:55 UTC, johnSamilin requested changes

2024-03-09 17:55 UTC, johnSamilin commented on package.json
> +        "compile:templates": "handlebars src/Components/Form/Form.hbs -f src/Components/Form/Form.precompiled.js"
почему только форма компилируется? пусть компилируются сразу все шаблоны, что есть в коде

2024-03-09 17:55 UTC, johnSamilin commented on server/index.js
> +app.use(express.static(path.join(__dirname, '..', 'node_modules')));
сервить из node_modules все еще ничего не нужно (и не нужно будет вообще)

2024-03-09 17:55 UTC, johnSamilin commented on src/Components/Form/Form.js
> +        this.#container.innerHTML = template(this.#config);
может быть outerHTML, чтобы лишних div-ов не образовывалось? сейчас каждый компонент будет обернут в div, который ни для какой цели не служит

2024-03-09 17:55 UTC, johnSamilin commented on src/Components/Form/Form.js
> +export default class Form {
весь этот класс с небольшими изменениями можно сделать базовым (BaseComponent) и наследовать все компоненты от него: `class Form extends BaseComponent { #templateName = 'Form' }`

2024-03-09 17:55 UTC, johnSamilin commented on src/Pages/LoginPage.js
> +            additionButtonText: 'Еще нет аккаунта?',
`onAdditionButtonClicked: this.redirectToRegistration`

2024-03-09 17:55 UTC, johnSamilin commented on src/Components/Form/Form.js
> +    render() {
вот здесь, если включать режим занудства, то можно поспорить. исходя из названия метода, render должен вернуть кусок html или созданный элемент с привязанными колбеками, но не добавлять его в DOM (но с этим тоже можно поспорить, так что это просто к сведению)

2024-03-09 17:55 UTC, johnSamilin commented on src/Components/Form/Form.js
> +        this.#config = config;
в конфиге вполне могут быть какие-то колбеки, которые нужно вызывать при каких-то событиях (например, при клике по кнопке _внутри этого компонента_)

2024-03-09 17:55 UTC, johnSamilin commented on src/Pages/RegisterPage.js
> +            additionButtonText: 'Уже есть аккаунт?',
`onAdditionButtonClicked: this.redirectToLogin`

2024-03-09 17:55 UTC, johnSamilin commented on src/index.html
> +    <link rel="stylesheet" href="./Components/Form/Form.css">
на будущее: вот сейчас у вас нет бандла и все стили и js для компонентов будут загружаться тут при старте приложения? а как быть, если компонентов 10000, а на стартовой странице нужны только 5?

2024-03-09 18:37 UTC, IvanNaum commented on src/Components/Form/Form.js
> +export default class Form {
fixed

2024-03-09 19:05 UTC, IvanNaum commented on src/Components/Form/Form.js
> +        this.#config = config;
fixed

2024-03-09 19:06 UTC, IvanNaum commented on src/Pages/LoginPage.js
> +            additionButtonText: 'Еще нет аккаунта?',
fixed

2024-03-09 19:11 UTC, IvanNaum commented on server/index.js
> +app.use(express.static(path.join(__dirname, '..', 'node_modules')));
Handlebars должен иметь глобальную область видимости, для этого мы добавляем его тут в index.html:
```html
<script src="/handlebars/dist/handlebars.runtime.js"></script>
```
Есть какой-то иной способ?

2024-03-09 19:12 UTC, IvanNaum commented on src/Pages/RegisterPage.js
> +            additionButtonText: 'Уже есть аккаунт?',
fixed

2024-03-09 19:27 UTC, IvanNaum commented on package.json
> +        "compile:templates": "handlebars src/Components/Form/Form.hbs -f src/Components/Form/Form.precompiled.js"
fixed

2024-03-09 19:37 UTC, IvanNaum commented on src/Components/Form/Form.js
> +        this.#container.innerHTML = template(this.#config);
добавил div.form-container в шаблон и добавил 
`this.#parent.innerHTML += container;`

нормально?

2024-03-09 20:54 UTC, johnSamilin commented on server/index.js
> +app.use(express.static(path.join(__dirname, '..', 'node_modules')));
Есть, грузить с cdn

2024-03-09 20:58 UTC, johnSamilin commented on src/Components/Form/Form.js
> +        this.#container.innerHTML = template(this.#config);
Да, вполне

2024-03-09 21:01 UTC, johnSamilin commented on src/Components/Form/Form.js
> +        this.#container.innerHTML = template(this.#config);
Только разве что заменить на https://developer.mozilla.org/ru/docs/Web/API/Element/insertAdjacentHTML

2024-03-10 06:55 UTC, johnSamilin approved these changes

2024-03-10 08:01 UTC, merged